<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Transaction;
use App\Models\Product;
use App\Models\User;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = User::first(); // Assuming at least one user exists

        $products = Product::take(5)->get(); // Take 5 products

        foreach ($products as $product) {
            $oldStock = $product->stock;
            $quantity = rand(1, 10); // Random quantity between 1 and 10
            $type = ['in', 'out', 'adjustment'][array_rand(['in', 'out', 'adjustment'])];

            $newStock = match ($type) {
                'in' => $oldStock + $quantity,
                'out' => max(0, $oldStock - $quantity),
                'adjustment' => $quantity,
            };

            Transaction::create([
                'product_id' => $product->id,
                'user_id' => $user->id,
                'type' => $type,
                'quantity' => $quantity,
                'old_stock' => $oldStock,
                'new_stock' => $newStock,
                'price' => $product->price,
                'reason' => 'Seeder generated',
                'notes' => 'Generated by TransactionSeeder',
            ]);

            $product->update(['stock' => $newStock]);
        }
    }
}